"use client";
import axios from "axios";
import toast from "react-hot-toast";
import { CgCloseR } from "react-icons/cg";
import { useState } from "react";
const roles = [["customer", "مشتری"], ["agent", "پشتیبان عمومی"], ["passive_agent", "پشتیبان پسیو"], ["active_agent", "پشتیبان اکتیو"], ["admin", "مدیر"]];
export default function CreatUser({ setShowCreateModal, showCreateModal, setIsChangeInfo }) {
 const [info,setInfo]=useState({role:"customer"}); const [saving,setSaving]=useState(false);
 const submit=async()=>{setSaving(true);try{const {data}=await axios.post("/api/users",info);if(data.success){toast.success("کاربر با موفقیت ساخته شد");setIsChangeInfo(v=>!v);setShowCreateModal(false)}}catch(e){toast.error(e.response?.data?.message||"ساخت کاربر ناموفق بود")}finally{setSaving(false)}};
 return <div dir="rtl" className="w-[min(94vw,34rem)] max-w-xl"><div className="mb-6 flex items-start justify-between"><div><h1 className="text-2xl font-black text-slate-900">افزودن کاربر جدید</h1><p className="mt-1 text-sm text-slate-500">حساب کاربری و سطح دسترسی را تعیین کنید</p></div><CgCloseR className="cursor-pointer text-slate-500" size={24} onClick={()=>setShowCreateModal(!showCreateModal)}/></div><div className="space-y-4"><label className="block text-sm font-bold text-slate-700">نام و نام خانوادگی<input onChange={e=>setInfo({...info,name:e.target.value})} placeholder="مثلاً امیرعباس عبدالرزاق" className="mt-2 h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/></label><label className="block text-sm font-bold text-slate-700">شماره تماس<input dir="ltr" onChange={e=>setInfo({...info,phone:e.target.value})} placeholder="09123456789" className="mt-2 h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 outline-none focus:border-blue-500"/></label><label className="block text-sm font-bold text-slate-700">نقش کاربر<select value={info.role} onChange={e=>setInfo({...info,role:e.target.value})} className="mt-2 h-12 w-full rounded-2xl border border-slate-200 bg-white px-4">{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className="mt-6 flex gap-3 border-t border-slate-100 pt-5"><button disabled={saving} onClick={submit} className="flex-1 rounded-2xl bg-gradient-to-l from-blue-600 to-cyan-500 px-5 py-3 font-bold text-white shadow-lg">{saving?"در حال ساخت...":"ساخت حساب کاربری"}</button><button onClick={()=>setShowCreateModal(false)} className="rounded-2xl border border-slate-200 px-5 py-3 font-bold">انصراف</button></div></div>;
}
