"use client";
import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";

const passiveTasks = ["بازدید و برداشت مسیرها و نودها", "اجرای کابل‌کشی و نصب کیستون/فیس‌پلیت", "نصب پچ‌پنل، رک و مدیریت کابل", "لیبل‌گذاری و تطبیق نودها با پچ‌پنل و سوئیچ", "تست فیزیکی و گزارش مغایرت‌ها"];
const activeTasks = ["نصب سوئیچ، روتر، اکسس‌پوینت و تجهیزات امنیتی", "تنظیم IP، Gateway، VLAN و DHCP/DNS", "تنظیم SSID و سیاست‌های پایه امنیتی", "تست اتصال و ثبت IP مدیریتی تجهیزات", "تهیه نسخه پشتیبان تنظیمات و تحویل دسترسی‌ها"];

export default function ProjectJobBriefAdmin({ projectId }) {
  const [items, setItems] = useState([]);
  const [drafts, setDrafts] = useState({});
  const load = async () => { try { const { data } = await axios.get(`/api/projects/${projectId}/assessments`); if (data.success) { setItems(data.assessments); setDrafts(Object.fromEntries(data.assessments.map((a) => [a._id, a.jobBrief || {}]))); } } catch {} };
  // Data loading is intentionally triggered when the project changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [projectId]);
  const update = (id, key, value) => setDrafts((old) => ({ ...old, [id]: { ...(old[id] || {}), [key]: value } }));
  const save = async (item, issue) => { try { await axios.patch(`/api/projects/${projectId}/assessments`, { assessmentId: item._id, jobBrief: drafts[item._id] || {}, jobBriefStatus: issue ? "issued" : "draft" }); toast.success(issue ? "ابلاغ برای پشتیبان ارسال شد" : "شرح وظایف ذخیره شد"); load(); } catch (error) { toast.error(error.response?.data?.message || "ذخیره ناموفق بود"); } };
  return <section dir="rtl" className="glass-panel space-y-5 p-5"><div><h2 className="text-xl font-black">ابلاغ شرح وظایف پروژه</h2><p className="mt-1 text-sm text-slate-500">پس از دریافت فرم ارزیابی، شرح وظایف هر کارشناس را مشخص و برای او ارسال کنید.</p></div>{items.length === 0 && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">هنوز کارشناس پسیو یا اکتیو برای این پروژه انتخاب نشده است.</p>}{items.map((item) => { const tasks = item.assigneeRole === "passive_agent" ? passiveTasks : activeTasks; const value = drafts[item._id] || {}; return <div key={item._id} className="rounded-2xl border border-slate-200 bg-white/70 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">{item.assignee?.name || "کارشناس"} — {item.assigneeRole === "passive_agent" ? "پسیو" : "اکتیو"}</h3><span className="text-xs text-slate-500">وضعیت فرم: {item.status}</span></div><label className="mt-4 block text-sm font-semibold">شرح کلی و برنامه اجرا<textarea value={value.summary || ""} onChange={(e) => update(item._id, "summary", e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 p-3" /></label><div className="mt-4 grid gap-2 md:grid-cols-2">{tasks.map((task, index) => <label key={task} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" checked={Boolean(value.tasks?.[index])} onChange={(e) => update(item._id, "tasks", { ...(value.tasks || {}), [index]: e.target.checked })} />{task}</label>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={value.startDate || ""} onChange={(e) => update(item._id, "startDate", e.target.value)} placeholder="تاریخ شروع" className="rounded-xl border border-slate-200 p-3" /><input value={value.deadline || ""} onChange={(e) => update(item._id, "deadline", e.target.value)} placeholder="مهلت پایان" className="rounded-xl border border-slate-200 p-3" /></div><div className="mt-4 flex flex-wrap justify-end gap-2 print:hidden"><button onClick={() => window.print()} className="rounded-xl border px-4 py-2 font-bold">چاپ / PDF</button><button onClick={() => save(item, false)} className="rounded-xl border px-4 py-2 font-bold">ذخیره پیش‌نویس</button><button onClick={() => save(item, true)} className="rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">ثبت و ابلاغ به پشتیبان</button></div></div>; })}</section>;
}
