"use client";

import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { PrintLetterhead, PrintSignaturePage } from "./PrintLetterhead";

const passiveTasks = ["بازدید و بررسی محل", "شناسایی مسیر کابل‌کشی و نقاط شبکه", "اجرای کابل‌کشی", "نصب Keystone / Faceplate / پریز", "نصب و پانچ Patch Panel", "نصب Rack و تجهیزات جانبی", "نصب Cable Manager و Patch Cord", "لیبل‌گذاری کابل‌ها و نودها", "تطبیق Patch Panel و Switch با نودها", "مرتب‌سازی کابل‌ها داخل Rack", "بررسی ظاهری و فیزیکی اجرا", "ثبت تعداد و محل نودها", "گزارش مغایرت با نقشه یا دستور کار"];
const activeTasks = ["نصب و جانمایی Switch", "نصب و تنظیم Router", "نصب و تنظیم Access Point", "نصب و تنظیم Firewall / تجهیزات امنیتی", "تنظیم IP و Gateway", "تنظیم VLAN", "تنظیم Access / Trunk Port", "تنظیم DHCP / DNS", "تنظیم Wi-Fi و SSID", "تنظیمات پایه امنیتی", "بررسی ارتباط تجهیزات و کلاینت‌ها", "ثبت IP مدیریتی و مشخصات تجهیزات", "تهیه Backup Configuration", "تحویل اطلاعات دسترسی طبق روش شرکت", "گزارش مشکلات و فعالیت‌های خارج از محدوده"];
const deliverables = ["گزارش فعالیت‌های انجام‌شده", "لیست تجهیزات نصب / راه‌اندازی‌شده", "Serial Number تجهیزات", "IP Address استفاده‌شده", "جدول ارتباط نودها با Patch Panel و Switch", "تنظیمات VLANهای مرتبط", "ثبت موارد انجام‌نشده یا خارج از محدوده", "ثبت مشکلات و اقدامات اصلاحی", "تصاویر قبل / حین / بعد اجرا", "Backup Configuration", "سایر مستندات مورد درخواست مسئول پروژه"];
const prerequisites = ["دسترسی به محل پروژه فراهم است", "تجهیزات و اقلام مورد نیاز در محل موجود است", "نقشه / دستور کار / اطلاعات فنی در اختیار کارشناس است", "دسترسی به رک، اتاق سرور و محل‌های اجرا فراهم است", "برق و زیرساخت مورد نیاز بررسی شده است", "هماهنگی با نماینده مشتری انجام شده است", "محدودیت‌های زمانی و ساعات مجاز کار اعلام شده است", "ملاحظات ایمنی و اجرایی محل اعلام شده است"];
const responsibilities = ["اجرای کار دقیقاً در محدوده شرح وظایف ابلاغ‌شده", "عدم انجام تغییرات خارج از شرح کار بدون هماهنگی", "رعایت اصول فنی و دستورالعمل‌های شرکت", "حفاظت از تجهیزات و اطلاعات مشتری", "عدم افشای Password، IP، Configuration و اطلاعات فنی", "گزارش فوری مشکل، مغایرت یا ریسک", "عدم جابه‌جایی تجهیزات مشتری بدون هماهنگی", "ارائه گزارش فعالیت‌ها طبق برنامه", "تحویل مستندات و اطلاعات مورد درخواست", "هماهنگی فوری در صورت تأخیر، توقف یا تغییر برنامه"];
const completionCriteria = ["تمام فعالیت‌های ابلاغ‌شده انجام یا وضعیت آنها کتبی گزارش شده است", "تجهیزات و اقلام نصب‌شده مرتب و در وضعیت مناسب هستند", "لیبل‌گذاری و شماره‌گذاری موارد ابلاغ‌شده انجام شده است", "تنظیمات ابلاغ‌شده انجام شده است", "تست‌های مورد درخواست انجام شده است", "مستندات و اطلاعات مورد درخواست ثبت شده است", "موارد باقی‌مانده یا مشکل‌دار گزارش شده است", "محل اجرای کار مرتب و تحویل شده است"];

function PersianDateInput({ value, onChange }) { return <input value={value || ""} onChange={(event) => onChange(event.target.value)} inputMode="numeric" placeholder="۱۴۰۵/۰۷/۱۸" className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 outline-none focus:border-blue-500" />; }
function Field({ label, value, onChange, multiline = false, date = false, children }) { return <label className={`block text-sm font-bold text-slate-700 ${multiline ? "md:col-span-2" : ""}`}><span>{label}</span>{children || (date ? <PersianDateInput value={value} onChange={onChange} /> : multiline ? <textarea value={value || ""} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 bg-white p-3 outline-none focus:border-blue-500" /> : <input value={value || ""} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 outline-none focus:border-blue-500" />)}</label>; }
function SelectField({ value, onChange, options }) { return <select value={value || ""} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3"><option value="">انتخاب کنید</option>{options.map((option) => <option key={option}>{option}</option>)}</select>; }
function Checklist({ title, items, values = {}, onChange, options = ["ابلاغ شد", "مشمول پروژه نیست"] }) { return <section className="glass-panel overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="text-lg font-black">{title}</h2></div><div className="divide-y divide-slate-100">{items.map((item, index) => <div key={item} className="grid gap-3 p-4 md:grid-cols-[2rem_1fr_13rem]"><span className="text-center text-sm text-slate-400">{(index + 1).toLocaleString("fa-IR")}</span><strong className="text-sm">{item}</strong><select value={values[item] || ""} onChange={(event) => onChange({ ...values, [item]: event.target.value })} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">انتخاب وضعیت</option>{options.map((option) => <option key={option}>{option}</option>)}</select></div>)}</div></section>; }
function Checkboxes({ items, values = {}, onChange }) { return <div className="mt-4 grid gap-2 md:grid-cols-2">{items.map((item) => <label key={item} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm"><input type="checkbox" checked={Boolean(values[item])} onChange={(event) => onChange({ ...values, [item]: event.target.checked })} />{item}</label>)}</div>; }
function Table({ title, rows, columns, data = {}, onChange }) { return <section className="glass-panel overflow-x-auto"><div className="border-b border-slate-100 p-5"><h2 className="text-lg font-black">{title}</h2></div><table className="min-w-[820px] w-full text-right text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-3">ردیف</th>{columns.map((column) => <th key={column.key} className="p-3">{column.label}</th>)}</tr></thead><tbody>{rows.map((label, index) => <tr key={index} className="border-t border-slate-100"><td className="p-3 text-center text-slate-400">{(index + 1).toLocaleString("fa-IR")}</td>{columns.map((column) => <td key={column.key} className="p-2">{column.type === "fixed" ? <span className="font-semibold">{label}</span> : column.type === "select" ? <select value={data[index]?.[column.key] || ""} onChange={(event) => onChange(index, { ...(data[index] || {}), [column.key]: event.target.value })} className="h-10 min-w-28 rounded-lg border border-slate-200 bg-white px-2"><option value="">انتخاب</option>{column.options.map((option) => <option key={option}>{option}</option>)}</select> : <input value={data[index]?.[column.key] || ""} onChange={(event) => onChange(index, { ...(data[index] || {}), [column.key]: event.target.value })} inputMode={column.type === "date" ? "numeric" : undefined} placeholder={column.type === "date" ? "۱۴۰۵/۰۷/۱۸" : ""} className="h-10 min-w-24 w-full rounded-lg border border-slate-200 bg-white px-2" />}</td>)}</tr>)}</tbody></table></section>; }

export default function ProjectJobBriefAdmin({ projectId }) {
  const [items, setItems] = useState([]);
  const [drafts, setDrafts] = useState({});
  const load = async () => { try { const { data } = await axios.get(`/api/projects/${projectId}/assessments`); if (data.success) { setItems(data.assessments); setDrafts(Object.fromEntries(data.assessments.map((assessment) => [assessment._id, assessment.jobBrief || {}]))); } } catch { toast.error("دریافت فرم‌های ابلاغ ناموفق بود"); } };
  // Data is intentionally refreshed only when the selected installation project changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [projectId]);
  const update = (id, key, value) => setDrafts((old) => ({ ...old, [id]: { ...(old[id] || {}), [key]: value } }));
  const updateTable = (id, key, index, value) => update(id, key, { ...(drafts[id]?.[key] || {}), [index]: value });
  const save = async (item, issue) => { try { await axios.patch(`/api/projects/${projectId}/assessments`, { assessmentId: item._id, jobBrief: drafts[item._id] || {}, jobBriefStatus: issue ? "issued" : "draft" }); toast.success(issue ? "ابلاغ برای پشتیبان ارسال شد" : "شرح وظایف ذخیره شد"); load(); } catch (error) { toast.error(error.response?.data?.message || "ذخیره ناموفق بود"); } };

  return <section dir="rtl" className="print-document space-y-5"><PrintLetterhead />{items.length === 0 ? <div className="glass-panel p-6 text-sm text-slate-500">هنوز کارشناس اکتیو یا پسیو برای این پروژه انتخاب نشده است.</div> : items.map((item) => { const value = drafts[item._id] || {}; return <section key={item._id} className="space-y-5"><div className="glass-panel print-header p-6"><div className="print-document-meta mb-4 hidden items-center justify-between border-b border-slate-300 pb-4 print:flex"><div><strong>فرم ابلاغ شرح وظایف و برنامه اجرای پروژه</strong><p>ابلاغ رسمی شرح وظایف و برنامه اجرا</p></div><span>کد سند: IT-RASAM-NET-FRM-002</span></div><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">IT-RASAM-NET-FRM-002</span><h2 className="mt-3 text-2xl font-black">فرم ابلاغ شرح وظایف و برنامه اجرای پروژه</h2><p className="mt-2 text-sm text-slate-500">کارشناس {item.assigneeRole === "passive_agent" ? "پسیو" : "اکتیو"}: {item.assignee?.name || "—"}</p></div>
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱. مشخصات پروژه و ابلاغ کار</h3><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="کد سند" value="IT-RASAM-NET-FRM-002" onChange={() => {}} /><Field label="نسخه" value="01" onChange={() => {}} /><Field label="تاریخ صدور (شمسی)" value={value.issueDate} onChange={(v) => update(item._id, "issueDate", v)} date /><Field label="شماره ابلاغ / فرم" value={value.issueNumber} onChange={(v) => update(item._id, "issueNumber", v)} /><Field label="شماره پروژه / قرارداد" value={value.contractNumber} onChange={(v) => update(item._id, "contractNumber", v)} /><Field label="وضعیت"><SelectField value={value.documentStatus} onChange={(v) => update(item._id, "documentStatus", v)} options={["اولیه", "اصلاحیه", "نهایی"]} /></Field><Field label="نام کارفرما / مشتری" value={value.customerName} onChange={(v) => update(item._id, "customerName", v)} /><Field label="محل اجرای پروژه" value={value.location} onChange={(v) => update(item._id, "location", v)} /><Field label="عنوان پروژه" value={value.projectTitle} onChange={(v) => update(item._id, "projectTitle", v)} /><Field label="مسئول پروژه ای‌تی رسام" value={value.projectOwner} onChange={(v) => update(item._id, "projectOwner", v)} /><Field label="کارشناس مسئول اجرا" value={value.agentName || item.assignee?.name} onChange={(v) => update(item._id, "agentName", v)} /><Field label="نوع فعالیت"><SelectField value={value.activityType} onChange={(v) => update(item._id, "activityType", v)} options={["Active", "Passive", "Active و Passive"]} /></Field><Field label="تاریخ ابلاغ (شمسی)" value={value.issueDateToAgent} onChange={(v) => update(item._id, "issueDateToAgent", v)} date /><Field label="تاریخ شروع برنامه‌ریزی‌شده (شمسی)" value={value.startDate} onChange={(v) => update(item._id, "startDate", v)} date /><Field label="تاریخ پایان برنامه‌ریزی‌شده (شمسی)" value={value.endDate} onChange={(v) => update(item._id, "endDate", v)} date /></div></section>
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۲. هدف و دامنه ابلاغ</h3><p className="mt-3 text-sm leading-7 text-slate-600">این فرم برای ابلاغ رسمی شرح وظایف، محدوده مسئولیت، اقلام قابل اجرا، زمان‌بندی، خروجی‌های مورد انتظار و الزامات اجرایی کارشناس تهیه شده است. کارشناس باید پیش از شروع عملیات، هرگونه ابهام، مغایرت، کمبود اطلاعات یا محدودیت اجرایی را اعلام کند.</p><Field label="شرح کلی و برنامه اجرای پروژه" value={value.summary} onChange={(v) => update(item._id, "summary", v)} multiline /></section>
      <Checklist title="۳. شرح وظایف Passive" items={passiveTasks} values={value.passiveTasks} onChange={(v) => update(item._id, "passiveTasks", v)} />
      <Checklist title="۴. شرح وظایف Active" items={activeTasks} values={value.activeTasks} onChange={(v) => update(item._id, "activeTasks", v)} />
      <Table title="۵. خروجی‌ها و مدارک مورد انتظار" rows={deliverables} data={value.deliverables} onChange={(i, v) => updateTable(item._id, "deliverables", i, v)} columns={[{ key: "output", label: "خروجی", type: "fixed" }, { key: "deadline", label: "مهلت (شمسی)", type: "date" }, { key: "status", label: "وضعیت" }]} />
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۶. برنامه زمان‌بندی اجرای عملیات</h3><p className="mt-2 text-sm text-slate-500">تغییر اساسی در زمان‌بندی باید پیش از اجرا با مسئول پروژه هماهنگ و ثبت شود.</p></section><Table title="جدول زمان‌بندی" rows={Array.from({ length: 10 })} data={value.schedule} onChange={(i, v) => updateTable(item._id, "schedule", i, v)} columns={[{ key: "activity", label: "شرح فعالیت" }, { key: "type", label: "نوع", type: "select", options: ["Active", "Passive", "هر دو"] }, { key: "start", label: "شروع (شمسی)", type: "date" }, { key: "end", label: "پایان (شمسی)", type: "date" }, { key: "duration", label: "زمان تخمینی" }, { key: "dependency", label: "توضیحات / وابستگی" }]} />
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۷. برنامه حضور و ساعات کاری</h3><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="روز / روزهای کاری" value={value.workDays} onChange={(v) => update(item._id, "workDays", v)} /><Field label="ساعت شروع" value={value.workStart} onChange={(v) => update(item._id, "workStart", v)} /><Field label="ساعت پایان" value={value.workEnd} onChange={(v) => update(item._id, "workEnd", v)} /><Field label="مجموع زمان پیش‌بینی‌شده" value={value.totalExpectedTime} onChange={(v) => update(item._id, "totalExpectedTime", v)} /><Field label="تعداد روز پیش‌بینی‌شده" value={value.expectedDays} onChange={(v) => update(item._id, "expectedDays", v)} /><Field label="کار خارج از ساعت عادی"><SelectField value={value.afterHours} onChange={(v) => update(item._id, "afterHours", v)} options={["دارد", "ندارد", "با هماهنگی قبلی"]} /></Field></div></section>
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۸. پیش‌نیازها و شرایط شروع کار</h3><Checkboxes items={prerequisites} values={value.prerequisites} onChange={(v) => update(item._id, "prerequisites", v)} /><div className="mt-4"><Field label="موارد فراهم‌نشده یا نیازمند پیگیری" value={value.pendingPrerequisites} onChange={(v) => update(item._id, "pendingPrerequisites", v)} multiline /></div></section>
      <Table title="۹. تجهیزات، ابزار و اقلام تحویلی به کارشناس" rows={Array.from({ length: 8 })} data={value.equipment} onChange={(i, v) => updateTable(item._id, "equipment", i, v)} columns={[{ key: "item", label: "شرح" }, { key: "count", label: "تعداد" }, { key: "received", label: "وضعیت تحویل", type: "select", options: ["سالم", "ناقص"] }, { key: "returnStatus", label: "وضعیت پایان کار" }, { key: "notes", label: "توضیحات" }]} />
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱۰. مسئولیت‌ها و الزامات کارشناس</h3><Checkboxes items={responsibilities} values={value.responsibilities} onChange={(v) => update(item._id, "responsibilities", v)} /></section>
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱۱. نحوه گزارش‌دهی</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="گزارش شروع کار"><SelectField value={value.startReport} onChange={(v) => update(item._id, "startReport", v)} options={["پیام / تماس", "گروه پروژه", "حضوری"]} /></Field><Field label="گزارش پیشرفت"><SelectField value={value.progressReport} onChange={(v) => update(item._id, "progressReport", v)} options={["روزانه", "پایان هر مرحله", "طبق دستور مسئول پروژه"]} /></Field><Field label="مشکل یا توقف" value="بلافاصله پس از شناسایی" onChange={() => {}} /><Field label="گزارش پایان کار" value="پایان عملیات و قبل از ترک محل" onChange={() => {}} /><Field label="تصاویر / مستندات"><SelectField value={value.mediaReporting} onChange={(v) => update(item._id, "mediaReporting", v)} options={["طبق درخواست", "پایان هر روز"]} /></Field><Field label="مرجع هماهنگی" value={value.coordinationContact} onChange={(v) => update(item._id, "coordinationContact", v)} /></div></section>
      <Table title="۱۲. تغییرات، موارد خارج از محدوده و مشکلات" rows={Array.from({ length: 5 })} data={value.changes} onChange={(i, v) => updateTable(item._id, "changes", i, v)} columns={[{ key: "issue", label: "شرح تغییر / مشکل" }, { key: "date", label: "تاریخ (شمسی)", type: "date" }, { key: "decision", label: "تصمیم مسئول پروژه" }, { key: "agentConfirmation", label: "تأیید کارشناس", type: "select", options: ["تأیید شد", "در انتظار"] }]} />
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱۳. معیارهای پایان کار</h3><Checkboxes items={completionCriteria} values={value.completionCriteria} onChange={(v) => update(item._id, "completionCriteria", v)} /></section>
      <Table title="۱۴. گزارش روزانه / ثبت زمان واقعی" rows={Array.from({ length: 8 })} data={value.dailyReports} onChange={(i, v) => updateTable(item._id, "dailyReports", i, v)} columns={[{ key: "date", label: "تاریخ (شمسی)", type: "date" }, { key: "activity", label: "شرح فعالیت" }, { key: "start", label: "شروع" }, { key: "end", label: "پایان" }, { key: "duration", label: "مدت" }, { key: "notes", label: "وضعیت / توضیحات" }]} />
      <Table title="۱۵. ثبت تأخیر، توقف یا عدم امکان اجرا" rows={Array.from({ length: 4 })} data={value.delays} onChange={(i, v) => updateTable(item._id, "delays", i, v)} columns={[{ key: "date", label: "تاریخ (شمسی)", type: "date" }, { key: "cause", label: "علت" }, { key: "duration", label: "مدت" }, { key: "action", label: "اقدام انجام‌شده" }, { key: "confirmation", label: "تأیید مسئول پروژه", type: "select", options: ["تأیید شد", "در انتظار"] }]} />
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱۶. تأیید دریافت و مطالعه شرح وظایف</h3><p className="mt-3 rounded-xl bg-slate-50 p-4 text-sm leading-7">اینجانب به عنوان کارشناس اجرای پروژه، تأیید می‌نمایم که پیش از شروع عملیات، شرح وظایف، محدوده کار، برنامه زمان‌بندی، خروجی‌های مورد انتظار، الزامات اجرایی و نحوه گزارش‌دهی مندرج در این فرم به اینجانب ابلاغ شده است. متعهد می‌گردم در صورت مشاهده ابهام، مانع، مغایرت یا فعالیت خارج از محدوده، پیش از اقدام موضوع را به مسئول پروژه اعلام نمایم.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="نام و نام خانوادگی کارشناس" value={value.agentConfirmationName || item.assignee?.name} onChange={(v) => update(item._id, "agentConfirmationName", v)} /><Field label="شماره تماس" value={value.agentPhone || item.assignee?.phone} onChange={(v) => update(item._id, "agentPhone", v)} /><Field label="سمت / تخصص" value={value.agentSpecialty} onChange={(v) => update(item._id, "agentSpecialty", v)} /><Field label="تاریخ دریافت ابلاغ (شمسی)" value={value.agentReceivedDate} onChange={(v) => update(item._id, "agentReceivedDate", v)} date /></div></section>
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱۷. تأیید مسئول پروژه</h3><p className="mt-2 text-sm leading-7 text-slate-600">هرگونه تغییر اساسی در محدوده یا زمان‌بندی باید در همین فرم یا مستندات رسمی مرتبط ثبت و تأیید گردد.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="نام و نام خانوادگی مسئول پروژه" value={value.managerName} onChange={(v) => update(item._id, "managerName", v)} /><Field label="سمت" value={value.managerRole} onChange={(v) => update(item._id, "managerRole", v)} /><Field label="تاریخ ابلاغ (شمسی)" value={value.managerIssueDate} onChange={(v) => update(item._id, "managerIssueDate", v)} date /></div></section>
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱۸. وضعیت نهایی ابلاغ</h3><Checkboxes items={["شرح وظایف و برنامه زمان‌بندی به‌طور کامل ابلاغ شد", "کارشناس قبل از شروع کار ابهام / مورد اصلاحی اعلام نمود", "اصلاحات مورد نیاز در بخش تغییرات ثبت شد", "کارشناس دریافت و مطالعه فرم را تأیید نمود"]} values={value.finalStatus} onChange={(v) => update(item._id, "finalStatus", v)} /><div className="mt-4"><Field label="توضیحات" value={value.finalNotes} onChange={(v) => update(item._id, "finalNotes", v)} multiline /></div></section>
      <section className="glass-panel p-5"><h3 className="text-lg font-black">۱۹. تأیید و امضاها</h3><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="نام کارشناس Active / Passive" value={value.signatureAgent} onChange={(v) => update(item._id, "signatureAgent", v)} /><Field label="نام مسئول / مدیر پروژه ای‌تی رسام" value={value.signatureManager} onChange={(v) => update(item._id, "signatureManager", v)} /><Field label="نام مدیر فنی / مدیر شرکت در صورت نیاز" value={value.signatureTechnicalManager} onChange={(v) => update(item._id, "signatureTechnicalManager", v)} /><Field label="تاریخ تأیید کارشناس (شمسی)" value={value.signatureAgentDate} onChange={(v) => update(item._id, "signatureAgentDate", v)} date /><Field label="تاریخ تأیید مسئول پروژه (شمسی)" value={value.signatureManagerDate} onChange={(v) => update(item._id, "signatureManagerDate", v)} date /><Field label="تاریخ تأیید مدیر فنی (شمسی)" value={value.signatureTechnicalManagerDate} onChange={(v) => update(item._id, "signatureTechnicalManagerDate", v)} date /></div><p className="mt-4 text-center text-xs text-slate-500">شرکت ای‌تی رسام – IT RASAM | این فرم همراه با گزارش‌های اجرایی و صورتجلسه تحویل نهایی پروژه بایگانی می‌شود.</p></section>
      <PrintSignaturePage documentTitle="فرم ابلاغ شرح وظایف و برنامه اجرای پروژه" projectName={value.projectTitle} parties={[{ title: "کارشناس اجرا", name: value.signatureAgent || value.agentName || item.assignee?.name }, { title: "مسئول پروژه ای‌تی رسام", name: value.signatureManager || value.managerName }, { title: "مدیر فنی / نماینده شرکت", name: value.signatureTechnicalManager }]} />
      <div className="project-form-actions glass-panel sticky bottom-4 flex flex-wrap justify-end gap-3 p-4 print:hidden"><button type="button" onClick={() => window.print()} className="rounded-xl border px-5 py-3 font-bold">چاپ / ذخیره PDF</button><button type="button" onClick={() => save(item, false)} className="rounded-xl border px-5 py-3 font-bold">ذخیره پیش‌نویس</button><button type="button" onClick={() => save(item, true)} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">ثبت و ابلاغ به پشتیبان</button></div>
    </section>; })}</section>;
}
