import { isValidObjectId } from "mongoose";
import Project from "@/models/installationProjects";
import ProjectHandover from "@/models/projectHandovers";
import ConnectDb from "@/utils/connectDB";
import getCurrentUser from "@/utils/auth";
import authorization from "@/utils/authorization";

export async function GET(req, { params }) { await ConnectDb(); const user = await getCurrentUser(); if (!user) return Response.json({ success: false, message: "ابتدا وارد شوید" }, { status: 401 }); const { projectId } = await params; if (!isValidObjectId(projectId)) return Response.json({ success: false, message: "شناسه پروژه معتبر نیست" }, { status: 400 }); const query = authorization(user, ["admin"]) ? { project: projectId } : { project: projectId, assignee: user._id }; const handovers = await ProjectHandover.find(query).populate("project", "name code status").populate("assignee", "name role").sort({ createdAt: -1 }).lean(); return Response.json({ success: true, handovers }); }
export async function POST(req, { params }) { await ConnectDb(); const user = await getCurrentUser(); if (!user || !authorization(user, ["admin"])) return Response.json({ success: false, message: "دسترسی غیرمجاز" }, { status: 403 }); const { projectId } = await params; const { assignee, assigneeRole } = await req.json(); if (!isValidObjectId(projectId) || !isValidObjectId(assignee) || !["passive_agent", "active_agent"].includes(assigneeRole)) return Response.json({ success: false, message: "اطلاعات صورتجلسه معتبر نیست" }, { status: 400 }); const item = await ProjectHandover.findOneAndUpdate({ project: projectId, assignee, assigneeRole }, { $setOnInsert: { project: projectId, assignee, assigneeRole } }, { upsert: true, new: true }); return Response.json({ success: true, handover: item }, { status: 201 }); }
export async function PATCH(req, { params }) { await ConnectDb(); const user = await getCurrentUser(); if (!user || !["admin", "passive_agent", "active_agent"].includes(user.role)) return Response.json({ success: false, message: "دسترسی غیرمجاز" }, { status: 403 }); const { projectId } = await params; const body = await req.json(); const filter = authorization(user, ["admin"]) ? { _id: body.handoverId, project: projectId } : { _id: body.handoverId, project: projectId, assignee: user._id }; const update = {}; if (body.data !== undefined) { update.data = body.data; update.status = body.status === "submitted" ? "submitted" : "assigned"; if (update.status === "submitted") update.submittedAt = new Date(); } if (authorization(user, ["admin"]) && ["approved", "rejected"].includes(body.status)) { update.status = body.status; update.approvedAt = body.status === "approved" ? new Date() : null; update.approvedBy = body.status === "approved" ? user._id : null; } const handover = await ProjectHandover.findOneAndUpdate(filter, update, { new: true }); if (!handover) return Response.json({ success: false, message: "صورتجلسه پیدا نشد" }, { status: 404 }); if (authorization(user, ["admin"]) && body.status === "approved") { const project = await Project.findById(projectId); const required = [project?.passiveAgent, project?.activeAgent].filter(Boolean).length; const approved = await ProjectHandover.countDocuments({ project: projectId, status: "approved" }); if (required > 0 && approved >= required) await Project.findByIdAndUpdate(projectId, { status: "archived" }); } return Response.json({ success: true, handover }); }
